### ISSUE TITLE
Does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by smihael** [hirschmann/nbfc#86]
I installed mono as in instructions, but nbfc still won't compile. Following errors occur:

Errors:

opt/nbfc-1.4.2/NoteBookFanControl.sln (Build) ->
(Build target) ->
opt/nbfc-1.4.2/Core/StagWare.Configurations/StagWare.FanControl.Configurations.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

        CSC: error CS0518: The predefined type `System.Object' is not defined or imported
        CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
        CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
        CSC: error CS0518: The predefined type `System.Single' is not defined or imported
        CSC: error CS0518: The predefined type `System.Double' is not defined or imported
        CSC: error CS0518: The predefined type `System.Char' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
        CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
        CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
        CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
        CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
        CSC: error CS0518: The predefined type `System.String' is not defined or imported
        CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
        CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.Void' is not defined or imported
        CSC: error CS0518: The predefined type `System.Array' is not defined or imported
        CSC: error CS0518: The predefined type `System.Type' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

**Comment by hirschmann** [comment]
I was able to reproduce this error.
For some reason the mono-complete package on Ubuntu 16.04 does only include assembies for .NET Framework 4.5, but NBFC targets v.4.0.

Fortunately you can override the target version:
`xbuild /p:Configuration=ReleaseLinux /p:TargetFrameworkVersion=v4.5 /p:TargetFrameworkProfile="" NoteBookFanControl.sln`

I'll probably upgrade the project to target v.4.5 soon.

**Comment by smihael** [comment]
That worked. Would be neice if you update it in the next release.

**Comment by hirschmann** [comment]
Fixed: d02e70534b4290d8a327ebb0d5d7f4bf7381c419
