### ISSUE TITLE
Build issue on LinuxMint 18.1

### ISSUE THREAD

**Issue by lunetic** [hirschmann/nbfc#250]
Hello,
on LinuxMint 18.1 with all updates I get these build errors:

/home/linux/nbfc/NoteBookFanControl.sln (Build) ->
(Build target) ->
/home/linux/nbfc/Tests/StagWare.FanControl.Tests/StagWare.FanControl.Tests.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	FanControlTests.cs(52,66): error CS8082: An argument to nameof operator cannot include sub-expression
	FanControlTests.cs(97,66): error CS8082: An argument to nameof operator cannot include sub-expression
	FanControlTests.cs(193,62): error CS8082: An argument to nameof operator cannot include sub-expression

	 4 Warning(s)
	 3 Error(s)

This is with nbfc 1.5.0.
With nbfc 1.5.3 I get even more errors and warnings.

mono-complete 4.2.1 and build-essential is installed.

Build on Ubuntu 16.04.2 works ok!

Any idea?

**Comment by Tilogorn** [comment]
Can confirm build errors on Linux Mint 18.1

Cloned current master, installed fresh mono-complete 4.2.1

	CSC: error CS0518: The predefined type `System.Object' is not defined or imported
	CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
	CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
	CSC: error CS0518: The predefined type `System.Single' is not defined or imported
	CSC: error CS0518: The predefined type `System.Double' is not defined or imported
	CSC: error CS0518: The predefined type `System.Char' is not defined or imported
	CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
	CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
	CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
	CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
	CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
	CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
	CSC: error CS0518: The predefined type `System.String' is not defined or imported
	CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
	CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
	CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
	CSC: error CS0518: The predefined type `System.Void' is not defined or imported
	CSC: error CS0518: The predefined type `System.Array' is not defined or imported
	CSC: error CS0518: The predefined type `System.Type' is not defined or imported
	CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
	CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
	CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
	CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
	CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
	CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
	CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
	CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

	 9 Warning(s)
	 31 Error(s)

**Comment by hirschmann** [comment]
The mono version in the Mint 18.1 repositories is too old.

There are multiple solutions to this problem:

- Update to Mint 18.2
- Build NBFC on a Distro with an up-to-date mono (e.g. a Ubuntu 17.04 VM) and copy the binaries to your Mint machine
- Open the NBFC solution in Monodevelop and disable all the test projects for the _ReleaseLinux_ build configuration

**Comment by hirschmann** [comment]
The problem should be fixed with  commit 3b1721f

**Comment by iguerendiain** [comment]
The problem is still present after the commit. Same error on LInux Mint 18.2

**Comment by hirschmann** [comment]
Commit 3b1721f fixes @lunetic's issue only.
@Tilogorn's issue is due to an outdated version of mono.

If you want to build NBFC on Linux, follow these instructions: https://github.com/hirschmann/nbfc/wiki/How-to-build-NBFC#build-on-linux

**Comment by iguerendiain** [comment]
I understand, however, you answerd @Tilogorn with "Update to Mint 18.2" as s possible solution and I wanted to let you know that trying to compile it on Linux Mint 18.2 yields the same result.

What version of Mono should I be using in order to successfully compile NBFC?

Thanks

**Comment by hirschmann** [comment]
I've successfully built nbfc on Ubuntu/mono 4.6.2, but you don't have to use that specific version.
It's usually easier to update to the latest version, following these instructions: http://www.mono-project.com/download/#download-lin
